version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
      - xpack.security.transport.ssl.enabled=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch
      - thread_pool.search.queue_size=500
      - processors=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '9200:9200'
    mem_limit: 4g
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - portainer

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    restart: unless-stopped
    ports:
      - '5601:5601'
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED="true"
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - XPACK_SECURITY_ENABLED="true"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    networks:
      - portainer
    depends_on:
      - elasticsearch

networks:
  portainer:
    name: portainer
    external: true
