version: '3'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    volumes:
      - /data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]
    networks:
      - portainer

  ollama-webui:
    container_name: ollama-webui
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    volumes:
      - /data/ollama-webui:/app/backend/data
    ports:
      - "3010:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
