#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    volumes:
      - ${DATA}/config:/var/lib/kafka/data
    user: root
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/var/lib/kafka/data  # Ensure log directory is correctly set
      - ALLOW_PLAINTEXT_LISTENER=yes  # Allow plaintext listener
    networks:
      - portainer

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8083:8083"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
